name: GitHub Pages

on:
  push:
    branches:
      - tex
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    container:
      image: texlive/texlive:latest-full
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          pdflatex ohno.tex
          cp ohno.tex index.html public/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: stammtisch-muenchen.dante.de
